version: '3.8' 

networks:
  prod_net:
    driver: bridge

services:
  serving-api:
    container_name: serving-api

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../data:/app/data
      - ../artifacts:/app/artifacts

    ports:
      - "8080:8000" 
      
    networks:
      - prod_net