version: '3.8' 

networks:
  serving_prod_net:
    external: true

services:
  webapp:
    container_name: webapp-api

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../data:/app/data
    
    ports:
      - "8081:8081"
    
    networks:
      - serving_prod_net
      
